# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: docs/source/dashboard.gif

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.0
    hooks:
      # Run the linter (only sorting imports for now)
      - id: ruff-check
        name: ruff sort imports
        args: [ --fix, --select=I ]
      - id: ruff-check
        name: ruff clean unused imports in notebooks
        args: [--select=F401]
        files: .*.ipynb$
      # Run the formatter.
      - id: ruff-format
        exclude: ^cpp/

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ^notebooks/
