name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@21e08f89c731f8d4e984827048035f8e7960cb13#egg=discrete-optimization
      - nbgitpuller
