name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@177d5e18998f789b255f43da65bc7a533cb15436#egg=discrete-optimization
      - nbgitpuller
