name: nb-do0.2.0-py3.9
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - git+https://github.com/airbus/discrete-optimization@b77bfdd1262c2cf88ec2ac1e51d9740eb1a908b7#egg=discrete-optimization
      - nbgitpuller
