name: Build discrete-optimization

env:
  MAIN_REPO_NAME: 'airbus/discrete-optimization'

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      do_version: ${{ steps.get_library_version.outputs.version }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: create requirements.txt so that pip cache with setup-python works
        run:
          echo "build" > requirements_build.txt
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements_build.txt
      - name: Install build dependencies
        run: pip install -U build
      - name: Build discrete-optimization (wheel + source code)
        run: python -m build
      - name: Upload as build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
      - name: get library version and save it
        id: get_library_version
        run: |
          wheelfile=$(ls ./dist/discrete_optimization*.whl)
          version=$(python -c "print('$wheelfile'.split('-')[1])")
          echo "version=$version"
          echo "version=$version" >> $GITHUB_OUTPUT

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.10", "3.13"]
    env:
      JOB_NAME: test (${{ matrix.os }}, ${{ matrix.python-version }})
      WORKER_ID: ${{ matrix.os }}-python${{ matrix.python-version }}
    name: test (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout discrete-optimization source code
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist
      - name: Install only discrete-optimization without extras
        run: |
          wheelfile=$(ls ./dist/discrete_optimization*.whl)
          python -m pip install -U pip
          pip install ${wheelfile}
          pip list

      - name: Install test dependencies
        run: |
          wheelfile=$(ls ./dist/discrete_optimization*.whl)

          pip install "${wheelfile}" "pytest<9.1.0" --group test

          pip list

      - name: Test non-regression
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_JOB_NAME: ${{ env.JOB_NAME }}
          TARGET_STEP_NAME: "Test non-regression"
        run: |
          pytest -v $(python tests/find_non_regression_tests.py) | python -u .github/scripts/parse_non_regression.py || true

      - name: Post a comment in the PR triggering the workflow
        if: github.event_name == 'pull_request' && hashFiles('./regressions_pr_comment.md') != ''
        uses: actions/github-script@v9.0.0
        with:
          script: |
            const fs = require('fs');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fs.readFileSync('./regressions_pr_comment.md', 'utf8')
            });

      - name: Upload nonregression report as artifact
        uses: actions/upload-artifact@v7
        with:
          name: regressions-${{ matrix.os }}-${{ matrix.python-version }}
          path: regressions.csv
          if-no-files-found: ignore

      - name: Test examples in docstrings
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_JOB_NAME: ${{ env.JOB_NAME }}
          TARGET_STEP_NAME: "Test examples in docstrings"
        run: |
          # Use unbuffered output (-u) so line logging indices accurately sync with stdout
          pytest --doctest-modules src -v | python -u .github/scripts/parse_doctest.py || true
